spring.application.name=Authentication
server.port=9001

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=vedavyaasmr
spring.datasource.password=admin123

spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=testingxyz123456@gmail.com
spring.mail.password=frke lppr oixr ncwq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=mailGroup