spring.application.name=Ingestor
server.port=9002

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/project_db
spring.datasource.username=vedavyaasmr
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql